name: ci-build-images

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Rustlang custom image build and push
        id: docker_build_rustlang_custom
        uses: docker/build-push-action@v2
        with:
          context: ./rust
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust:1.0
      - name: Nushell custom image (for ebay-seller-bot) build and push
        id: docker_build_ebay_seller_bot
        uses: docker/build-push-action@v2
        with:
          context: ./ebay-seller-bot
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ebay-seller-bot:1.0
      #- name: Nushell custom image (for Odds API controller) build and push
      #  id: docker_build_odds_api_ctl
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./odds-api-ctl
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/odds-api-ctl:1.0
      - name: Blackarch custom image build and push
        id: docker_build_blackarch_custom
        uses: docker/build-push-action@v2
        with:
          context: ./blackarch-custom
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blackarch-custom:1.0